### ISSUE TITLE
Add pod/node labels

### ISSUE THREAD

**Issue by benjaminjb** [kubernetes/metrics#27]
I'm using metrics-server to keep track of certain CPU/memory usage, but I'd like to aggregate on pod labels. 

I asked this over here https://github.com/kubernetes-sigs/metrics-server/issues/347 and was told that I should ask it here.

**Comment by ehashman** [comment]
/close

@benjaminjb Please file this issue against the kubernetes/kubernetes repo. This repo is just a mirrored copy of https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/metrics
