### ISSUE TITLE
Support mutli-cluster for HPA

### ISSUE THREAD

**Issue by wudebao** [kubernetes/metrics#29]
Multi-cluster is a reasonable scenario in a production environment，but now，can not support it，can you support mutli-cluster for HPA ？

**Comment by serathius** [comment]
Please reach out to SIG-autoscaling or file an Issue in https://github.com/kubernetes/kubernetes for feature requests for HPA.

**Comment by wudebao** [comment]
ok, it will open an Issue in https://github.com/kubernetes/kubernetes for this feature for HPA
