### ISSUE TITLE
Need a document on how to use this for custom metrics api server

### ISSUE THREAD

**Issue by kumudt** [kubernetes/metrics#5]
Hi

We are actually planning to implement this custom metrics API server on our cluster and use it for pod auto scaling. So, looking forward to an introductory document or a blog post on how to use this project.

Thanks.

**Comment by DirectXMan12** [comment]
You'll want to take a look at https://github.com/kubernetes-incubator/custom-metrics-apiserver.  It contains boilerplate for writing an API server to serve the custom metrics API.  For an example of an API server using the boilerplate, check out https://github.com/directxman12/k8s-prometheus-adapter.

I'll add a note to the README about the boilerplate.
